//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestImmobilier.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFrc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFrc() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebGestImmobilier.Models.App_LocalResources.ResourceFrc", typeof(ResourceFrc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un appartement.
        /// </summary>
        public static string add_apartment {
            get {
                return ResourceManager.GetString("add_apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un chambre.
        /// </summary>
        public static string add_bedroom {
            get {
                return ResourceManager.GetString("add_bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;une maison.
        /// </summary>
        public static string add_house {
            get {
                return ResourceManager.GetString("add_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un terrain.
        /// </summary>
        public static string add_land {
            get {
                return ResourceManager.GetString("add_land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un proprietaire.
        /// </summary>
        public static string add_owner {
            get {
                return ResourceManager.GetString("add_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un studio.
        /// </summary>
        public static string add_studio {
            get {
                return ResourceManager.GetString("add_studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;un utilisateur .
        /// </summary>
        public static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appartement.
        /// </summary>
        public static string apartment {
            get {
                return ResourceManager.GetString("apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant de l&apos;appartment.
        /// </summary>
        public static string apartment_id {
            get {
                return ResourceManager.GetString("apartment_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libelle de l&apos;appartement.
        /// </summary>
        public static string apartment_label {
            get {
                return ResourceManager.GetString("apartment_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des appartements.
        /// </summary>
        public static string apartment_list {
            get {
                return ResourceManager.GetString("apartment_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Gestion Immobiliere.
        /// </summary>
        public static string app_management {
            get {
                return ResourceManager.GetString("app_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chambre.
        /// </summary>
        public static string bedroom {
            get {
                return ResourceManager.GetString("bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Chambres.
        /// </summary>
        public static string bedroom_list {
            get {
                return ResourceManager.GetString("bedroom_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un appartement.
        /// </summary>
        public static string delete_apartment {
            get {
                return ResourceManager.GetString("delete_apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;une chambre.
        /// </summary>
        public static string delete_bedroom {
            get {
                return ResourceManager.GetString("delete_bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;une maison.
        /// </summary>
        public static string delete_house {
            get {
                return ResourceManager.GetString("delete_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d;un terrain.
        /// </summary>
        public static string delete_land {
            get {
                return ResourceManager.GetString("delete_land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un proprietaire.
        /// </summary>
        public static string delete_owner {
            get {
                return ResourceManager.GetString("delete_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un studio.
        /// </summary>
        public static string delete_studio {
            get {
                return ResourceManager.GetString("delete_studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un utilisateur.
        /// </summary>
        public static string delete_user {
            get {
                return ResourceManager.GetString("delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à prenom.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maison.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Superficie de la maison.
        /// </summary>
        public static string house_area {
            get {
                return ResourceManager.GetString("house_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description de la masion.
        /// </summary>
        public static string house_description {
            get {
                return ResourceManager.GetString("house_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant maison.
        /// </summary>
        public static string house_id {
            get {
                return ResourceManager.GetString("house_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des maisons.
        /// </summary>
        public static string house_list {
            get {
                return ResourceManager.GetString("house_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation de la maison.
        /// </summary>
        public static string house_location {
            get {
                return ResourceManager.GetString("house_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix de la maison.
        /// </summary>
        public static string house_price {
            get {
                return ResourceManager.GetString("house_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maisons.
        /// </summary>
        public static string houses {
            get {
                return ResourceManager.GetString("houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à terrain.
        /// </summary>
        public static string land {
            get {
                return ResourceManager.GetString("land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Superficie du terrain.
        /// </summary>
        public static string land_area {
            get {
                return ResourceManager.GetString("land_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description du terrain.
        /// </summary>
        public static string land_description {
            get {
                return ResourceManager.GetString("land_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant du terrain.
        /// </summary>
        public static string land_id {
            get {
                return ResourceManager.GetString("land_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des terrains.
        /// </summary>
        public static string land_list {
            get {
                return ResourceManager.GetString("land_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation du terrain.
        /// </summary>
        public static string land_location {
            get {
                return ResourceManager.GetString("land_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix du terrain.
        /// </summary>
        public static string land_price {
            get {
                return ResourceManager.GetString("land_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de terrains.
        /// </summary>
        public static string land_type {
            get {
                return ResourceManager.GetString("land_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de dcouche .
        /// </summary>
        public static string number_of_bathroom {
            get {
                return ResourceManager.GetString("number_of_bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de chambre.
        /// </summary>
        public static string number_of_bedrooms {
            get {
                return ResourceManager.GetString("number_of_bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de cuisine.
        /// </summary>
        public static string number_of_kitchens {
            get {
                return ResourceManager.GetString("number_of_kitchens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de pieces.
        /// </summary>
        public static string number_of_pieces {
            get {
                return ResourceManager.GetString("number_of_pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Salle .
        /// </summary>
        public static string number_of_room {
            get {
                return ResourceManager.GetString("number_of_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de toilettes.
        /// </summary>
        public static string number_of_toilets {
            get {
                return ResourceManager.GetString("number_of_toilets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proprietaire.
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse du proprietaire.
        /// </summary>
        public static string owner_address {
            get {
                return ResourceManager.GetString("owner_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant du proprietaire.
        /// </summary>
        public static string owner_id {
            get {
                return ResourceManager.GetString("owner_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des proprietaire.
        /// </summary>
        public static string owner_list {
            get {
                return ResourceManager.GetString("owner_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studio.
        /// </summary>
        public static string studio {
            get {
                return ResourceManager.GetString("studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description du studio.
        /// </summary>
        public static string studio_description {
            get {
                return ResourceManager.GetString("studio_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des studios.
        /// </summary>
        public static string studio_list {
            get {
                return ResourceManager.GetString("studio_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localisation du studio.
        /// </summary>
        public static string Studio_location {
            get {
                return ResourceManager.GetString("Studio_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix du studio.
        /// </summary>
        public static string studio_price {
            get {
                return ResourceManager.GetString("studio_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à identifiant du studio.
        /// </summary>
        public static string studo_id {
            get {
                return ResourceManager.GetString("studo_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise a jour d&apos;un appartement.
        /// </summary>
        public static string update_apartment {
            get {
                return ResourceManager.GetString("update_apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise a jour d&apos;une Chambre.
        /// </summary>
        public static string update_bedroom {
            get {
                return ResourceManager.GetString("update_bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise a jour d&apos;une Maison.
        /// </summary>
        public static string update_house {
            get {
                return ResourceManager.GetString("update_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise a jour d&apos;un terrain.
        /// </summary>
        public static string update_land {
            get {
                return ResourceManager.GetString("update_land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise a jour d&apos;un proprietaire.
        /// </summary>
        public static string update_owner {
            get {
                return ResourceManager.GetString("update_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise a jour d&apos;un studio.
        /// </summary>
        public static string update_studio {
            get {
                return ResourceManager.GetString("update_studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIse a jour d&apos;un utilisateur .
        /// </summary>
        public static string update_user {
            get {
                return ResourceManager.GetString("update_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identiant.
        /// </summary>
        public static string user_id {
            get {
                return ResourceManager.GetString("user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string user_login {
            get {
                return ResourceManager.GetString("user_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom .
        /// </summary>
        public static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de téléphone.
        /// </summary>
        public static string user_phone {
            get {
                return ResourceManager.GetString("user_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenu.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
